server:
  port: 8000
  
eureka:  client:    register-with-eureka: true  
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:  application:    name: api-gateway
  cloud:    gateway:
      default-filters:      - name: GlobalFilter
        args:
          baseMessage: Spring Cloud Gateway GlobalFilter
          preLogger: true
          postLogger: true      routes:      - id: user-service-01
        #uri: http://127.0.0.1:8081
        uri: lb://USERSERVICE-01
        predicates:
        - Path=/userservice-01/**        filters:
        - AddRequestHeader=first-request, first-request-header2        - AddResponseHeader=first-response, first-response-header2
        - name: CustomFilter
        
      - id: userservice-02
        #uri: http://127.0.0.1:8082
        uri: lb://USERSERVICE-02
        predicates:        - Path=/userservice-02/**        filters:
        - AddRequestHeader=second-request, second-request-header2
        - AddResponseHeader=second-response, second-response-header2
        - name: CustomFilter
        - name: LoggingFilter
          args:
            baseMessage: Hello World!
            preLogger: true
            postLogger: false
                      