server:
  port: 8000
  
eureka:  client:    register-with-eureka: true  
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
spring:  application:    name: api-gateway
  cloud:    gateway:
      default-filters:      - name: GlobalFilter
        args:
          baseMessage: Spring Cloud Gateway GlobalFilter
          preLogger: true
          postLogger: true      routes:      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user-service/**
              - id: userservice-02
        #uri: http://127.0.0.1:8082
        uri: lb://USERSERVICE-02
        predicates:        - Path=/userservice-02/**        filters:
        - AddRequestHeader=second-request, second-request-header2
        - AddResponseHeader=second-response, second-response-header2
        - name: CustomFilter
        - name: LoggingFilter
          args:
            baseMessage: Hello World!
            preLogger: true
            postLogger: false
                      