server:
  port: 8888
  
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wonsakku/spring-cloud-inflearn-config.git
#          username: [your username]
#          password: [your password]

          
