server:
  port: 8888
  
spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: ${user.home}/Desktop/Work/native/file-repo
          search-locations: C:\wonsik\etc\class\native-file-repo
        git:
          uri: https://github.com/wonsakku/spring-cloud-inflearn-config.git
#          username: [your username]
#          password: [your password]

          
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
        
        
        